lists/urls.py
from django.conf.urls import patterns, url,include

urlpatterns = patterns('',
    url(r'', include('django.contrib.auth.urls', namespace='auth')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^new_member_list/$', 'lists.views.new_member_list', name='new_member_list'),
    url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^new$', 'lists.views.new_list', name='new_list'),
    url(r'^logout_view/$', 'lists.views.logout_view', name='logout_view'),
)

superlists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()
urlpatterns = patterns('',
    url(r'', include('django.contrib.auth.urls', namespace='auth')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^logout_view/$', 'lists.views.logout_view', name='logout_view'),
    url(r'^FAQ.html', 'lists.views.faq', name='faq'),
    url(r'^new_member_list', 'lists.views.new_member_list', name='new_member_list'),
    url(r'^slides.html', 'lists.views.slides', name='slides'),
    url(r'^motivation.html', 'lists.views.motivation', name='motivation'),
    url(r'^modeling.html', 'lists.views.modeling', name='modeling'),
    url(r'^testlogin.html', 'lists.views.testlogin', name='testlogin'),
    url(r'^overview.html', 'lists.views.overview', name='overview'),
    url(r'^lists/', include('lists.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

lists/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from lists.queryvoter import query
from lists.queryvoter import query_cols
#from django.contrib.auth import get_user_model
#User = get_user_model()

def date8dig_to_string(date):
    date=str(date)
    yr=date[0:4]
    month=date[4:6]
    day=date[6:8]
    return month+'/'+day+'/'+yr

def checkreg(regdate,d):
    for t in ['P','G']:
        for yr in range(2003,2015): 
            if yr < regdate//10000:
                d[t+str(yr)] = -1

class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])
    @staticmethod
    def create_ny_voter(d, prob,list_):
        checkreg(d['regdate'],d)
        Voter.objects.create(
                    username = d['username'],
                    lastname = (d['lastname'] or '').title(),
                    firstname = (d['firstname'] or '').title(),
                    middlename = (d['middlename'] or '').title(),
                    suffix = d['suffix'],
                    city = (d['city'] or '').title(),
                    zip = d['zip'],
                    DOB = date8dig_to_string(d['DOB']),
                    gender = d['gender'],
                    party = d['party'],
                    countycode = d['countycode'],
                    legdistrict = d['legdistrict'],
                    towncity = (d['towncity'] or '').title(),
                    #congressdistrict = d['congressdistrict'],
                    lastvote = date8dig_to_string(d['lastvote']),
                    regdate = date8dig_to_string(d['regdate']),
                    P2003 = d['P2003'],
                    P2004 = d['P2004'],
                    P2005 = d['P2005'],
                    P2006 = d['P2006'],
                    P2007 = d['P2007'],
                    P2008 = d['P2008'],
                    P2009 = d['P2009'],
                    P2010 = d['P2010'],
                    P2011 = d['P2011'],
                    P2012 = d['P2012'],
                    P2013 = d['P2013'],
                    P2014 = d['P2014'],
                    G2003 = d['G2003'],
                    G2004 = d['G2004'],
                    G2005 = d['G2005'],
                    G2006 = d['G2006'],
                    G2007 = d['G2007'],
                    G2008 = d['G2008'],
                    G2009 = d['G2009'],
                    G2010 = d['G2010'],
                    G2011 = d['G2011'],
                    G2012 = d['G2012'],
                    G2013 = d['G2013'],
                    G2014 = d['G2014'],
#                    nyid = d['nyid'],
                    prob=prob,
                    list=list_, 
                    )


    @staticmethod
    def create_new_twitt(username, item_firstname, item_lastname, item_zipcode='', list_=''):
        if not list_:
            list_ = List.objects.create()
            #this should be the username for authenticated User above (not friend)!
            person_ = Person.objects.create(firstname=item_firstname, lastname=item_lastname, list=list_)
        # find_nearby_zips(item_zipcode)
        (cols,rows,prob) = query(item_firstname, item_lastname, item_zipcode)
        for i,row in enumerate(rows):
            d = dict(zip(cols,row))
            d['username']=username
            List.create_ny_voter(d,prob[i],list_)
        return list_

    @staticmethod
    def create_new(item_firstname, item_lastname, item_zipcode=''):
        list_ = List.objects.create()
        person_ = Person.objects.create(firstname=item_firstname, lastname=item_lastname, list=list_)
        # find_nearby_zips(item_zipcode)
        (cols,rows,prob) = query(item_firstname, item_lastname, item_zipcode)
        
        state = 'newyork'
        if state == 'ohio':
            # column names: head -1  SWVF_1_44.TXT| perl -pe 's/,/\n/g' |grep GENERAL |perl -pe 's/-//g'|perl -pe 's/\///g'
            for row in rows:
                # these could be extracted from the dictionary version with a **
                Voter.objects.create(firstname=item_firstname, lastname=item_lastname,
                                 byr = row[0],
                                 GENERAL11072000=row[1],
                                 GENERAL11062001=row[2],
                                 GENERAL11052002=row[3],
                                 GENERAL11042003=row[4],
                                 GENERAL11022004=row[5],
                                 GENERAL11082005=row[6],
                                 GENERAL11072006=row[7],
                                 GENERAL11062007=row[8],
                                 GENERAL12112007=row[9],
                                 GENERAL11042008=row[10],
                                 GENERAL11182008=row[11],
                                 GENERAL11032009=row[12],
                                 GENERAL11022010=row[13],
                                 GENERAL11082011=row[14],
                                 GENERAL11062012=row[15],
                                 GENERAL11052013=row[16],
                                 list=list_,
                                 )
    
        elif state == 'newyork':
            for i,row in enumerate(rows):
                d = dict(zip(cols,row))
                d['username']=''
                List.create_ny_voter(d,prob[i],list_)
            
        return list_


##########################################################
class Person(models.Model):
    firstname = models.CharField(default='', max_length=100)
    lastname = models.CharField(default='', max_length=100)
    zipcode = models.IntegerField(default=None, null=True)
    list = models.ForeignKey(List, default=None)

    def __str__(self):
        return self.lastname

class Voter(models.Model):
    username = models.CharField(default='', max_length=100, null=True)
    lastname = models.CharField(default='', max_length=100, null=True)
    firstname = models.CharField(default='', max_length=100, null=True)
    middlename = models.CharField(default='', max_length=100, null=True)
    suffix = models.CharField(default='', max_length=3, null=True)
    city = models.CharField(default='', max_length=100, null=True)
    zip = models.IntegerField(default='0', null=True)
    DOB = models.CharField(default='', max_length=20, null=True)
    gender = models.CharField(default='', max_length=3)
    party = models.CharField(default='', max_length=100)
    countycode = models.IntegerField(default='0', null=True)
    legdistrict = models.IntegerField(default='0', null=True)
    towncity = models.CharField(default='', max_length=100, null=True)
    lastvote =  models.CharField(default='', max_length=20, null=True)
    regdate = models.CharField(default='', max_length=20, null=True)
    P2003 = models.IntegerField(default='0')
    P2004 = models.IntegerField(default='0')
    P2005 = models.IntegerField(default='0')
    P2006 = models.IntegerField(default='0')
    P2007 = models.IntegerField(default='0')
    P2008 = models.IntegerField(default='0')
    P2009 = models.IntegerField(default='0')
    P2010 = models.IntegerField(default='0')
    P2011 = models.IntegerField(default='0')
    P2012 = models.IntegerField(default='0')
    P2013 = models.IntegerField(default='0')
    P2014 = models.IntegerField(default='0')
    G2003 = models.IntegerField(default='0')
    G2004 = models.IntegerField(default='0')
    G2005 = models.IntegerField(default='0')
    G2006 = models.IntegerField(default='0')
    G2007 = models.IntegerField(default='0')
    G2008 = models.IntegerField(default='0')
    G2009 = models.IntegerField(default='0')
    G2010 = models.IntegerField(default='0')
    G2011 = models.IntegerField(default='0')
    G2012 = models.IntegerField(default='0')
    G2013 = models.IntegerField(default='0')
    G2014 = models.IntegerField(default='0')
    #nyid = models.IntegerField(default='0')
    prob = models.FloatField(default='-1.0')
    list = models.ForeignKey(List, default=None)
    #person = models.ForeignKey(Person, default=None)
    # ohio
#    firstname = models.CharField(default='', max_length=100)
#    lastname = models.CharField(default='', max_length=100)
#    byr = models.IntegerField(default='0')
#    GENERAL11072000=models.CharField(default='', max_length=10)
#    GENERAL11062001=models.CharField(default='', max_length=10)
#    GENERAL11052002=models.CharField(default='', max_length=10)
#    GENERAL11042003=models.CharField(default='', max_length=10)
#    GENERAL11022004=models.CharField(default='', max_length=10)
#    GENERAL11082005=models.CharField(default='', max_length=10)
#    GENERAL11072006=models.CharField(default='', max_length=10)
#    GENERAL11062007=models.CharField(default='', max_length=10)
#    GENERAL12112007=models.CharField(default='', max_length=10)
#    GENERAL11042008=models.CharField(default='', max_length=10)
#    GENERAL11182008=models.CharField(default='', max_length=10)
#    GENERAL11032009=models.CharField(default='', max_length=10)
#    GENERAL11022010=models.CharField(default='', max_length=10)
#    GENERAL11082011=models.CharField(default='', max_length=10)
#    GENERAL11062012=models.CharField(default='', max_length=10)
#    GENERAL11052013=models.CharField(default='', max_length=10)

    class Meta:
        ordering = ['-prob','lastname']

lists/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.fields import TextInput, NumberInput
from django.core.exceptions import ValidationError

from lists.models import Person, Voter, List

class ItemForm(ModelForm):
    zipcode = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': '[optional zip code]', 'class': 'form-control input-lg'}),required = False )

    class Meta:
        model = Person
        fields = ['firstname','lastname']
        widgets = {
             'firstname': TextInput(attrs={
                 'placeholder': 'first name',
                  'class': 'form-control input-lg'
             }),
             'lastname': TextInput(attrs={
                 'placeholder': 'last name',
                 'class': 'form-control input-lg'
             }),
         }
        error_messages = {
            'firstname': {'required': 'first name is required'},
            'lastname': {'required': 'last name is required'},
        }


class NewListForm(ItemForm):
    def save(self, owner=''):
        return List.create_new(item_firstname=self.cleaned_data['firstname'], 
                               item_lastname=self.cleaned_data['lastname'],
                               item_zipcode=self.cleaned_data['zipcode']
                               )

lists/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model

User = get_user_model()

from lists.forms import ItemForm, NewListForm
from lists.models import List

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})
def faq(request):
    return render(request, 'FAQ.html')
def motivation(request):
    return render(request, 'motivation.html')
def modeling(request):
    return render(request, 'modeling.html')
#######junk
def testlogin(request):
    return render(request, 'testlogin.html')
def overview(request):
    return render(request, 'overview.html')
def slides(request):
    return render(request, 'slides.html')
#######^junk

def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid(): #this is a django form built-in for checking required
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    if request.method == 'POST':
        return redirect(list_)
    return render(request, 'list.html', {'list': list_})

from django.contrib.auth import logout as auth_logout
from lists.socialnetworks.twitter import get_twitter_friends
from lists.models import List
def new_member_list(request):
    context = {}
    twitter_result =  get_twitter_friends(request)
    if isinstance(twitter_result,str):
        return render(request, 'twitter_error.html',{'err': twitter_result})
    else:
        twitter_friends_list = twitter_result
    if not request.user.is_authenticated():
        return render(request, 'home.html')
    list_ = ''
    for tfriend in twitter_friends_list:
        list_ = List.create_new_twitt(tfriend['username'],
                                tfriend['firstname'],
                                tfriend['lastname'],
                                item_zipcode='', 
                                list_=list_,
                                )
    return render(request, 'list.html', {'list': list_})

def logout_view(request):
    auth_logout(request)
    return redirect('/')
    

lists/templates/FAQ.html
{% extends 'basenoj.html' %}

{% block header_text %}{% endblock %}
{% block middle_text %}

<h2>Frequently asked questions</h2> <p>
<h4>Why doesn't X work?</h4> <p>
This page is very much pre-alpha form. It exists as a demo only at this point. If you have stumbled upon it, please come back in a couple of months for the complete, interesting, and functional version. 
<h4>What are your data sources?</h4> <p>
In general, voting histories have to be requested directly from Security of State offices with each state having different rules and fees for aquiring the data. Allowed uses of said data vary by state, but the data can never be used for commercial purposes.
<!--<a href="http://www2.sos.state.oh.us/pls/voter/f?p=111:1:0::NO:RP:P1_TYPE:STATE">Ohio <a>-->
 <p>
{% endblock %}

{% block extra_content %}{% endblock %}

lists/templates/analytics.html
{% extends 'basenoj.html' %}

{% block other_css %}
    <link href="/static/nv.d3.css" rel="stylesheet" media="screen">
{% endblock %}
{% block header_text %}{% endblock %}
{% block middle_text %}

<h2>Voter likelihood modeling in New York State</h2> <p>
Voting probabilities are calculated based on a regularized logistic regression performed on a random subset of 1 million voters, with features being the past ten years of voting. The model was fit on the 2014 midterm elections with K-fold cross-validation on 70% of that data; testing on the remaining 30% shows an area under the ROC curve of 0.85. Relative voter engagement is remarkably stable between elections so the model is also predictive (with similar success) of other midterm elections. 
<p>
Presidential turnout predictions and other details to come, or they are available on request.
<p> 
<h2>Other data stories</h2> <p>
This section describes interesting properties of voting data. More to come.
<p>
<h4>Variables that were predictive of voting in 2012</h4> <p>
By relating Census data to voter participation data at the zip code level, we can associate features of the electorate with voting likelihood. The plot below shows how strongly variables from the 2008-2012 American Community Survey are predictive of voter participation in the Ohio 2012 general election.
<p>


<style>
#chart svg {
  height: 400px;
}
</style>
<div id="chart">
  <svg></svg>
</div>

{% endblock %}
{% block form_action %}{% endblock %}
{% block extra_content %}{% endblock %}
{% block other_js %} 
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="/static/nv.d3.min.js"></script>
<script>
nv.addGraph(function() {
  var chart = nv.models.discreteBarChart()
      .x(function(d) { return d.label })    //Specify the data accessors.
      .y(function(d) { return d.value })
      .staggerLabels(true)    //Too many bars and not enough room? Try staggering labels.
      .tooltips(false)        //Don't show tooltips
      .showValues(true)       //...instead, show the bar value right on top of each bar.
      .transitionDuration(350)
      ;
  chart.yAxis
    .axisLabel('Relative predictive power') //should grab from coeffData key
    .axisLabelDistance(40);

  d3.select('#chart svg')
      .datum(coeffData())
      .call(chart);

 /* chart.rotateLabels(-45)
  chart.margin({bottom: 60});
  var xTicks = d3.select('.nv-x.nv-axis > g').selectAll('g');
  xTicks
    .selectAll('text')
    .attr('transform', function(d,i,j) { return 'translate (-10, 25) rotate(-90 0,0)' }) ;
*/

  nv.utils.windowResize(chart.update);

  return chart;
});

//Each bar represents a single discrete quantity.
function coeffData() {
    return [
        {
        key: "Relative Coefficients",
        values: [
{"label" : "pop_tot", "value" : -0.087114 }
,
{"label" : "housing_medianval", "value" : 0.253063 }
,
{"label" : "household_income", "value" : 0.399524 }
,
{"label" : "household_size", "value" : -0.294706 }
,
{"label" : "household_single_percent", "value" : -0.167984 }
,
{"label" : "education_BAormore_percent", "value" : 0.152768 }
,
{"label" : "citizen_notusa_percent", "value" : -0.036418 }
,
{"label" : "language_english_percent", "value" : 0.127378 }
,
{"label" : "black_frac", "value" : 0.250262 }
,
{"label" : "housing_vacant_frac", "value" : -0.012364 }
,
{"label" : "commute_ptransit_frac", "value" : 0.037805 }
,
{"label" : "commute_car_frac", "value" : 0.005095 }
,
{"label" : "avg_age2014", "value" : 0.162022 }
]
        }
      ]
}
</script>
<p>
<script>
/*
d3.json('/static/cumulativeLineData.json', function(data) {
  nv.addGraph(function() {
    var chart = nv.models.cumulativeLineChart()
                  .x(function(d) { return d[0] })
                  .y(function(d) { return d[1]/100 }) //adjusting, 100% is 1.00, not 100 as it is in the data
                  .color(d3.scale.category10().range())
                  .useInteractiveGuideline(true)
                  ;

     chart.xAxis
        .tickValues([1078030800000,1122782400000,1167541200000,1251691200000])
        .tickFormat(function(d) {
            return d3.time.format('%x')(new Date(d))
          });

    chart.yAxis
        .tickFormat(d3.format(',.1%'));

    d3.select('#chart svg')
        .datum(data)
        .call(chart);

    //TODO: Figure out a good way to do this automatically
    nv.utils.windowResize(chart.update);

    return chart;
  });
});
*/
</script>
{% endblock %}

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>friend your vote</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">
    <link href="/static/starter-template.css" rel="stylesheet">
</head>

<body>

    <div class="container">
      <!-- # this is the top bar -->
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Friend Your Vote</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active">
            <li><a href="http://www.friendyourvote.com/overview.html">Overview</a></li> 
            <li><a href="http://www.friendyourvote.com/motivation.html">Motivation</a></li>  
            <li><a href="http://www.friendyourvote.com/modeling.html">Modeling</a></li>  
            <li><a href="http://www.friendyourvote.com/FAQ.html">FAQ</a></li>  
            <li><a href="http://www.samleitner.com">Author</a></li> 
          </ul>
        </div><!--/.nav-collapse -->
      </nav>
      
      <div class="row marketing">
        <!-- # this is the container for the form -->
        <div class="col-lg-6">
          <h2>{% block header_text %}{% endblock %}</h2>
          {% block list_form %}
          {% endblock %}
        </div>
        <p><br><p>
        <!-- this is the results table or just a bar -->
        <div class="row">
          <div class="table-responsive col-md-6">
            {% block table %}
            {% endblock %}
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
          </div>
          <div
               class="fb-like"
               data-share="true"
               data-width="400"
               data-show-faces="true">
          </div>
        </div>
           
        <div align="right">
          <a href="https://twitter.com/share" class="twitter-share-button" data-text="Are your votes are lonely? ">Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script> 
        </div>

        <center> <a href="http://www.friendyourvote.com/overview.html">Overview</a>  |  
          <a href="http://www.friendyourvote.com/motivation.html">Motivation</a>  |  <a href="http://www.friendyourvote.com/modeling.html">Modeling</a>  |  <a href="http://www.friendyourvote.com/FAQ.html">FAQ</a>  |  <a href="http://www.samleitner.com">Author</a>
        </center>
        <br><p><br>
    </div>

<script src="/static/jquery-1.11.1.min.js"></script>
<script src="/static/jquery.dataTables.min.js"></script>
<link href="/static/jquery.dataTables.css" rel="stylesheet">
<link href="/static/dataTables.bootstrap.js">
<script src="/static/list.js"></script>
{% load eztables %}
<script>
$(document).ready(function() {
    $('#id_list_table').dataTable({
"order": [[ 0, "desc" ]],
"columnDefs": [{ "visible": false, "targets": [3] }],
"pageLength": 200,
"paging": false

    });
} );
</script>

</body>
<!--Google analytics-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-26899774-3', 'auto');
  ga('send', 'pageview');

</script>
</html>

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}
{% endblock %}

{% block list_form %}
<h2>Registered Voters</h2>
The table below lists registered voters in New York State, with rows colored by expected probability of participating in the 2016 presidential election. N/A indicates elections before the voter was locally registered. The table is searchable by birthdate (xx/xx/xxxx), but birthdate is not shown to protect voter privacy.
</div>
<div class="col-lg-6">
<br><br><br>
Note that predicted likelihoods are based on a voters entire history, including election data not displayed in the table. The data is subject to updates to 2014 turnout.<br>
<span class="label label-success">>75%</span> likely voter
<!--<span class="label label-info">75%-90%</span> likely -->
<span class="label label-warning">25%-75%</span> mobilizable voter
<span class="label label-danger"><25%</span> unlikely voter
<br>
<h3><a href="/">restart search</a></h3>
</div>
{% endblock %}
{% block table %}
<br>
<table id="id_list_table" class="table table-hover table-bordered ">
      <thead>
        <tr> 
          <th rowspan="2" style="vertical-align:middle;"> voting likelihood </th>
          <th rowspan="2" style="vertical-align:middle;"> name </th>
          <th rowspan="2" style="vertical-align:middle;"> location </th>
          <th rowspan="2" style="vertical-align:middle;"> birth date </th>
          <th colspan="4" style="vertical-align:middle;"><center> voting history </center></th> 
          <th rowspan="2" style="vertical-align:middle;"> contact </th> 
        </tr>
        <tr> 
          <th>2014</th><th>2013</th><th>2012</th><th>2011</th>
        </tr>
      </thead>
      <tbody>
        {% for voter in list.voter_set.all %}
          {% if voter.prob > 89.5 %}
          <tr class="success">
          {% elif voter.prob > 74.5 %}
          <tr class="success"> <!--info-->
          {% elif voter.prob > 24.5  %}
          <tr class="warning">
          {% else %}
          <tr class="danger">
           {% endif %}


           <!--<td> {{ forloop.counter }} </td> -->
           <td> <center>{{ voter.prob|floatformat:"0"  }}% </center></td>
             <td> {{ voter.firstname }} {{ voter.middlename }} {{ voter.lastname }}</td> 
           <td> {{ voter.city }}, NY {{ voter.zip }} </td>
           <td>{{ voter.DOB }}</td>

           {% if voter.G2014 == 1 %}
               <td>  ✓ </td>
           {% elif voter.G2014 == 0 %}
               <td> - </td>
           {% elif voter.G2014 == -1 %}
               <td> N/A </td>
           {% endif %}
           {% if voter.G2013 == 1 %}
               <td> ✓ </td>
           {% elif voter.G2013 == 0 %}
               <td> - </td>
           {% elif voter.G2013 == -1 %}
               <td> N/A </td>
           {% endif %}
           {% if voter.G2012 == 1 %}
               <td> ✓ </td>
           {% elif voter.G2012 == 0 %}
               <td> - </td>
           {% elif voter.G2012 == -1 %}
               <td> N/A </td>
           {% endif %}
           {% if voter.G2011 == 1 %}
               <td> ✓ </td>
           {% elif voter.G2011 == 0 %}
               <td> - </td>
           {% elif voter.G2011 == -1 %}
               <td> N/A </td>
           {% endif %}
           <td> <a href="https://twitter.com/intent/tweet?screen_name={{ voter.username }}&text=vote%20with%20me%20on%20Tuesday?" data-related="SamNLeitner">Tweet @{{ voter.username }}</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
           </td>

          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if list.owner %}
        <p>List owner: <span id="id_list_owner">{{ list.owner.email }}</span><p>
    {% endif %}
{% endblock %}

{% block extra_content %}

{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block list_form %}{% endblock %}

{% block header_text %}My Lists{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
Not functional for the moment.
<!--

    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>

    <h2>Lists shared by other users</h2>
    <ul>
    {% for list in owner.shared_lists.all %}
        <li>
            <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            ({{ list.owner.email }})
        </li>
    {% endfor %}
    </ul>

-->
{% endblock %}

lists/templates/overview.html
{% extends 'basenoj.html' %}

{% block other_css %}
    <link href="/static/nv.d3.css" rel="stylesheet" media="screen">
{% endblock %}
{% block header_text %}{% endblock %}
{% block middle_text %}


<h2>Site Usage</h2> 

Friend your vote is a tool to help mobilize New York State voters by providing easy access to public voting records along with some context, and twitter interaction. 
The site can either be used to look up specific voters, or you can use the twitter sign-in to match the full name of all the Twitter users you follow, to a voter database. Visit again in the near future for a screen-cast that will step through the site's main features.
<p>
{% endblock %}
{% block form_action %}{% endblock %}
{% block extra_content %}{% endblock %}
{% block other_js %} 
{% endblock %}